### ISSUE TITLE
"Cannot find node-webkit in your Applications folder"

### ISSUE THREAD

**Issue by kthornbloom** [micc83/Nuwk#9]
Hi there! I was really excited to find Nuwk, but couldn't get it running. I have both nw.js and nuwk in my applications folder, but when I run nuwk, it gives an orange error message across the top saying "Cannot find node-webkit in your Applications folder". Any clues?

Running osx 10.9.5

**Comment by micc83** [comment]
Hello @kthornbloom ,

I'm sorry but Nuwk hasn't been updated to work with NW.js so it's still looking for node-webkit. Hopefully I should be able to fix it by the end of the month, in the while you could give a look on the source code of Nuwk!. 
- Right click on the Nuwk! file
- Clic on "Show Package Content"
- Open `Content/Resources/app.nw` folder
- Edit `js/model.js` file row 11accordingly

        nwPath : '/Applications/node-webkit.app',

I'm not sure it will work but it's worth a try.
Alex

**Comment by kthornbloom** [comment]
Thanks for the quick reply, Alex! To give you an update- your suggestion worked to get nuwk to see nwjs.app. I selected the folder where my files reside, and hit Build Project.

Unfortunately after building, an error message says it can't be opened because it may be damaged or incomplete. Am I supposed to zip the files up first or anything like that?

**Comment by micc83** [comment]
Nope, the building process SHOULD be completely automated. One thing, when you say "I selected the folder where my files reside" what do you mean?
Nuwk create its custom folder structure for projects. Try to build a new project using Nuwk and build it. If it works all you have to do is to move your project files inside the proper folder created by Nuwk.

**Comment by kthornbloom** [comment]
Thanks, I tried that and although it says it was successful, the app won't run due to being 'damaged'. It's really too bad! Nuwk seems to be the easiest method I've found so far.

**Comment by micc83** [comment]
If you are willing to give it another try. Open the Info.plist file within the Resources folder and edit it as follow:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>BuildMachineOSBuild</key>
  <string>12C3006</string>
  <key>CFBundleDevelopmentRegion</key>
  <string>en</string>
  <key>CFBundleDisplayName</key>
  <string>{{name}}</string>
  <key>CFBundleExecutable</key>
  <string>nwjs</string>
  <key>CFBundleIconFile</key>
  <string>nw.icns</string>
  <key>CFBundleIdentifier</key>
  <string>io.nwjs.nw</string>
  <key>CFBundleInfoDictionaryVersion</key>
  <string>6.0</string>
  <key>CFBundleName</key>
  <string>{{name}}</string>
  <key>CFBundlePackageType</key>
  <string>APPL</string>
  <key>CFBundleShortVersionString</key>
  <string>{{version}}</string>
  <key>DTSDKBuild</key>
  <string>11E52</string>
  <key>DTSDKName</key>
  <string>macosx10.7</string>
  <key>DTXcode</key>
  <string>0452</string>
  <key>DTXcodeBuild</key>
  <string>4G2008a</string>
  <key>LSFileQuarantineEnabled</key>
  <true/>
  <key>LSMinimumSystemVersion</key>
  <string>10.6.0</string>
  <key>NSPrincipalClass</key>
  <string>NSApplication</string>
  <key>NSSupportsAutomaticGraphicsSwitching</key>
  <true/>
  <key>SCMRevision</key>
  <string>239963</string>
</dict>
</plist>
```

**Comment by kthornbloom** [comment]
HEY! It works. Thanks a lot man.

**Comment by micc83** [comment]
Great,  you saved me the time to test it :)
Il 02/mar/2015 18:04 "Kevin Thornbloom" <notifications@github.com> ha
scritto:
